expt: 37.1
notes: GSL on trimodal (transfer learning); features - resnet50, optical flow, openpose (after smoothing new normalized)
save_path: /home/nrk1787/slt_phase2/models/multimodal_transformer/data/37.1

data:
    sl: gsl
    vocab: /home/nrk1787/slt_phase2/Datasets/GSL/phoenix2014T.vocab.txt
    train: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.train.corpus.csv
    val: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.dev.corpus.csv
    test: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.test.corpus.csv
    vid_col: name
    caption_col: translation
    features:
        f1:
            name: resnet50
            path: /home/nrk1787/slt_phase2/Datasets/GSL/resnet
        f2: 
            name: optical_flow
            path: /home/nrk1787/slt_phase2/Datasets/GSL/optical_flow/after_resnet50
        f3: 
            name: openpose
            path: /home/nrk1787/slt_phase2/Datasets/GSL/openpose/new_normalised
    pad_index: 1

model:
    type: mult_fusion
    batch_size: 8
    shuffle: True
    f1_only: True
    f2_only: True
    f3_only: True
    optimizer:
        lr: 1.0e-3
        betas:
            - 0.9
            - 0.998
        eps: 1.0e-8
        weight_decay: 0.001
        amsgrad: False
    scheduler:
        mode: max
        patience: 8
        factor: 0.7
        threshold_mode: abs
        verbose: False
    loss:
        smoothing: 0.0
        translation_normalization_mode: 'batch'
        translation_loss_weight: 1.0
        batch_multiplier: 1
    encoder:
        emb_dim: 256
        attn_dropout_mem: 0
        attn_dropout_f1: 0.1
        attn_dropout_f2: 0.0
        attn_dropout_f3: 0.0
        num_layers: 3
        num_heads: 8
        attn_mask: True
        embed_dropout: 0.1
        relu_dropout: 0.1
        res_dropout: 0.1
    decoder:
        emb_dim: 768
        scale: False
        norm_type: 'batch'
        activation_type: softsign
        num_layers: 3
        num_heads: 8
        max_out_len: 30

training:
    resume: True
    transfer_learning: False
    ckpt: /home/nrk1787/slt_phase2/models/multimodal_transformer/data/37/ckpt/100.ckpt
    epochs: 500
    save_model_epoch: 5
    save_sent_epoch: 5
    learning_rate_min: 1.0e-7
    capture_wts: False

misc:
    seed: 42
    use_cuda: True
    max_output_length: 30
    wandb: True
