expt: debug
notes: Mult- Encoder (joeynmt); Features used - joeynmt, openpose, kmeans
save_path: /home/nrk1787/slt_phase2/models/multimodal_transformer/data/debug

data:
    sl: gsl
    vocab: /home/nrk1787/slt_phase2/Datasets/GSL/phoenix2014T.vocab.txt
    train: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.train.corpus.csv
    val: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.dev.corpus.csv
    test: /home/nrk1787/slt_phase2/Datasets/GSL/PHOENIX-2014-T.test.corpus.csv
    vid_col: name
    caption_col: translation
    features:
        f1:
            name: joeynmt
            path: /home/nrk1787/slt_phase2/Datasets/GSL/joeynmt
        f2: 
            name: openpose
            path: /home/nrk1787/slt_phase2/Datasets/GSL/openpose/After_smoothing_not_normalized
        f3: 
            name: kmeans
            path: /home/nrk1787/slt_phase2/Datasets/GSL/kmeans
    pad_index: 1

model:
    type: mult_joeynmt
    batch_size: 8
    shuffle: True
    f1_only: True
    f2_only: True
    f3_only: True
    optimizer:
        lr: 1.0e-3
        betas:
            - 0.9
            - 0.998
        eps: 1.0e-8
        weight_decay: 0.001
        amsgrad: False
    scheduler:
        mode: max
        patience: 8
        factor: 0.7
        threshold_mode: abs
        verbose: False
    loss:
        smoothing: 0.0
        translation_normalization_mode: 'batch'
        translation_loss_weight: 1.0
        batch_multiplier: 1
    encoder:
        emb_dim: 512 
        dropout: 0.1
        num_layers: 3
        num_heads: 8
        embed_dropout: 0.1
        scale: False
        norm_type: batch
        activation_type: softsign
        ff_size: 2048
    decoder:
        emb_dim: 512
        scale: False
        norm_type: batch
        activation_type: softsign
        num_layers: 3
        num_heads: 8
        max_out_len: 30

training:
    resume: False
    epochs: 500
    save_model_epoch: 5
    save_sent_epoch: 5
    learning_rate_min: 1.0e-7
misc:
    seed: 42
    use_cuda: True
    max_output_length: 30
    wandb: False



